### ISSUE TITLE
Travis CI build might be useful

### ISSUE THREAD

**Issue by ericcurtin** [spook/service#1]
Since you are targeting a large number of platforms a Travis CI build would likely prove handy if you planned on writing tests:

https://github.com/ericcurtin/ape/blob/master/.travis.yml
https://travis-ci.org/ericcurtin/ape

It's free infrastructure. I'd be happy to create the .travis.yml file, if you set up the account.

**Comment by spook** [comment]
Cool, thanx, I'll check it out!
